# Build settings
markdown: redcarpet
highlighter: pygments
gems:
  - king
  
# Site settings
title: "just、king"
description: > # this means to ignore newlines until "email:"
   just、king的博客

email: a-mail@mail.mail
#blog logo
logo: "/assets/images/df_logo.jpg"
# blog cover
cover: "/assets/images/cA4aKEIPQrerBnp1yGHv_IMG_9534-3-2.jpg"

name: 'just、king'
author: 'just、king'
author_image: "/assets/images/author.jpg"

paginate:	5

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

# social icons and sharing options
social:
  - icon:	github
    url:	https://github.com/Hx1993
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

